### ISSUE TITLE
Error while running the container

### ISSUE THREAD

**Issue by indravd** [OblivionCloudControl/xebia-email-signature#18]
Get the following error when running the container via cli after I filled in all the fields:
```
Traceback (most recent call last):
  File "/usr/local/bin/xebia-signature-cli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/xebia_email_signature/signature.py", line 374, in main
    employee_details = add_formatted_phone(employee_details)
  File "/usr/local/lib/python3.9/site-packages/xebia_email_signature/signature.py", line 106, in add_formatted_phone
    result = {k: v for k, v in contact_details.items()}
AttributeError: 'NoneType' object has no attribute 'items'
```

I do not experience this issue when I run the container via the web client.

**Comment by indravd** [comment]
Closing this issue since it's no longer relevant
